In [138]:
import numpy as np

In [139]:
x = np.array([0, 5, 3, 1, 0])
y = np.array([5, 10, 8, 6, 0])

In [140]:
points = np.vstack([y, x])
points

array([[ 5, 10,  8,  6,  0],
       [ 0,  5,  3,  1,  0]])

In [141]:
points = points.T
points

array([[ 5,  0],
       [10,  5],
       [ 8,  3],
       [ 6,  1],
       [ 0,  0]])

In [142]:
size = len(x)
size

5

In [143]:
raddi = np.zeros(size)
raddi

array([0., 0., 0., 0., 0.])

In [144]:
raddi[0] = np.inf
raddi

array([inf,  0.,  0.,  0.,  0.])

In [145]:

for i in range(1, size):
    idx = i
    raddi[i] = np.min(np.sum(np.square(points[:idx] - points[i]), 1))
    # print(np.min(np.sum(np.square(points[:idx] - points[i]), 1)))
    # print(raddi[i])
    print(points[:idx])
    print(points[i])
    print(np.sum(np.square(points[:idx] - points[i]), 1))
    print(np.min(np.sum(np.square(points[:idx] - points[i]), 1)))

[[5 0]]
[10  5]
[50]
50
[[ 5  0]
 [10  5]]
[8 3]
[18  8]
8
[[ 5  0]
 [10  5]
 [ 8  3]]
[6 1]
[ 2 32  8]
2
[[ 5  0]
 [10  5]
 [ 8  3]
 [ 6  1]]
[0 0]
[ 25 125  73  37]
25


In [146]:

raddi

array([inf, 50.,  8.,  2., 25.])

In [147]:
x = np.array(x[np.argpartition(raddi, -3)[-3:]])
y = np.array(y[np.argpartition(raddi, -3)[-3:]])

In [148]:
print(x)
print(y)

[0 0 5]
[ 0  5 10]


In [7]:
import numpy as np
k = 4
feat_dim = 8 * 4 * 4
fv = np.zeros((k, feat_dim))
fv.shape

(4, 128)

In [8]:
16 // 2

8

In [11]:
test = np.pad(fv, 16 // 2)

In [12]:
test.shape

(20, 144)

In [13]:
np.zeros((4, 4, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [14]:
a = [1, 2, 3, 4, 5, 6]

In [17]:
a[np.argpartition(a, 2)[:2][0]]

1

In [18]:
from utils import *
path = '../data/Episcopal Gaudi/test3a.jpg'

In [22]:
image = load_image('../data/Mount Rushmore/test2a.jpg')
image.shape

(1944, 2592, 3)

In [23]:
image = cv2.resize(image, (0, 0), fx=0.5, fy=0.5)
image.shape

(972, 1296, 3)

In [ ]:
image = load_image('../data/Sacre Coeur/test5a.jpg')